= ConfigurationService [[configuration_service]]

image:https://img.shields.io/maven-central/v/org.meeuw.configuration/mihxil-configuration.svg[Maven Central,link=https://search.maven.org/artifact/org.meeuw.configuration/mihxil-configuration]
image:https://www.javadoc.io/badge/org.meeuw.configuration/mihxil-configuration.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw.configuration/mihxil-configuration]

`ConfigurationService` is responsible for managing the `Configuration` thread locals.

Like this it can be consulted

.Accessing configuration
[source,java]
----
include::../mihxil-math/src/test/java/org/meeuw/test/examples/ConfigurationExample.java[tag=import]
...
include::../mihxil-math/src/test/java/org/meeuw/test/examples/ConfigurationExample.java[tag=access, indent=0]
----
This would however probably mainly be used in _implementations_.

Actual configuration can be done in two basically distinct ways.

- a new configuration object can be set as a thread local
- global default configuration object can be set

.temporary overrides
[source,java]
----
include::../mihxil-math/src/test/java/org/meeuw/test/examples/ConfigurationExample.java[tag=configurationService,indent=0]
----

There are some utilities in `ConfigurationService` that makes this process a bit easier.

.temporary overrides utilities
[source, java]
----
include::../mihxil-math/src/test/java/org/meeuw/test/examples/ConfigurationExample.java[tag=closable,indent=0]

----

Global defaults can be set similarly

.setting global defaults
[source,java]
----
include::../mihxil-math/src/test/java/org/meeuw/test/examples/ConfigurationExample.java[tag=global,indent=0]
----

ConfigurationService itself is not actually math related, and is released in a separate artifact.

