= ConfigurationService [[configuration_service]]

image:https://img.shields.io/maven-central/v/org.meeuw.configuration/mihxil-configuration.svg[Maven Central,link=https://search.maven.org/artifact/org.meeuw.configuration/mihxil-configuration]
image:https://www.javadoc.io/badge/org.meeuw.configuration/mihxil-configuration.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw.configuration/mihxil-configuration]

`ConfigurationService` is responsible for managing the `Configuration` thread locals.

Like this it can be consulted

.Accessing configuration
[source,java]
----

import org.meeuw.configuration.Configuration;
import org.meeuw.configuration.ConfigurationService;
import org.meeuw.math.text.configuration.NumberConfiguration;
...

Configuration configuration = ConfigurationService.getConfiguration();
NumberConfiguration aspect = configuration.getAspect(NumberConfiguration.class);
int minimalExponent = aspect.getMinimalExponent();
----
This would however probably mainly be used in _implementations_.

Actual configuration can be done in two basically distinct ways.

- a new configuration object can be set as a thread local
- global default configuration object can be set

.temporary overrides
[source,java]
----
Unresolved directive in README-source.adoc - include::mihxil-math/src/test/java/org/meeuw/test/examples/ConfigurationExample.java[tag=configurationService,indent=-]
----

There are some utilities in `ConfigurationService` that makes this process a bit easier.

.temporary overrides utilities
[source, java]
----
 ConfigurationService.withConfiguration((con) ->
  con.configure(TestConfigurationAspect.class,
             (tc) -> tc.withSomeInt(5))
     .configure(NumberConfiguration.class,
             (tc) -> tc.withMinimalExponent(3))
, () -> {
// code

 });
----

Global defaults can be set similarly

.setting global defaults
[source,java]
----
 ConfigurationService.defaultConfiguration((con) ->
  con.configure(NumberConfiguration.class, c -> c.withMinimalExponent(4))
     .configure(TestConfigurationAspect.class, c -> c.withSomeInt(-1))
 );
----

ConfigurationService itself is not actually math related, and is released in a separate artifact.
