[#demo_solver]
= Solver

The same idea as my link:https://meeuw.org/flippo/flippo.html[very first applet]. Solving the '24 flippo game'.

Give the desired outcome number, and a few input numbers, and it will find the possible ways to get it using those input numbers.

[NOTE]
====
This combines several aspects of this project:

- It uses 'rational numbers' to make all operations exact
- It uses the permutation group to permute all combinations of values
- It uses the Abstract Syntax Tree feature to combine values and operators
- It uses some features of the Field, e.g. to perform operators generically.
- It will currently use the field of `RationalNumbers` _or_ `GaussianRationals` if the input contains a complex number. I might add also support for `RealField` (and for example also support the POW operator)

====

++++
<form id="solver" class="demo">
  <label for="solver_outcome">Desired outcome:</label>
  <input type="text"
         required="required"
         id="solver_outcome"  list="solver_outcome-examples"
         data-parser="parseOutcome"
         data-error-message="enter one (fractional) number"
         value="24"/>
  <datalist id="solver_outcome-examples">
     <option value="24">the original 24 game value</option>
     <option value="4 1/3">fractions are allowed</option>
     <option value="41"></option>
     <option value="120">a nicer value for 5 input numbers</option>
   </datalist>
   <br />
  <label for="solver_input">Input numbers:</label>
  <input type="text" id="solver_input"
         list="solver_input-examples"
         required="required"
         placeholder="Enter a few numbers (probably no more than 5)"
          data-parser="parseInput"
          data-error-message="enter one or more (fractional) numbers"
         />
   <datalist id="solver_input-examples">
     <option value="8 8 3 3">a hard one to make 24 with</option>
     <option value="4 7 7 7 8" >a hard one to make 120 with</option>

   </datalist>
  <br />
  <output id="solver_output"  for="solver_result solver_numbers"> </output>
  <br />
  <button name="submit">go!</button>
</form>
++++

[%collapsible, title=java source code]
====
This is the source code for the above.
[source,java]
----
include::src/main/java/org/meeuw/math/demo/Solver.java[indent=-]
----
====
[%collapsible, title=javascript]
====
This is the source code for the above.
[source,javascript]
----
include::resources/js/solver.js[indent=-,tag=solver]
----
====
