= Demo
:docinfo: private
:source-highlighter: coderay


These are a running demos (using link:https://cheerpj.com/docs/getting-started/Java-library[cheerpj]). It doesn't always work.

== Solver

The same idea as my link:https://meeuw.org/flippo/flippo.html[very first applet]. Solving the '24 flippo game'.

Give the desired outcome number, and a few input numbers, and it will find the possible ways to get it using those input numbers.

This combines several aspects of this project:

- It uses 'rational numbers' to make all operations exact
- It uses the permutation group to permute all combinations of values
- It uses the Abstract Syntax Tree feature to combine values and operators
- It uses some features of the group of 'RationalNumbers', e.g. to perform operators generically.

++++
<form id="solver" class="demo">
  <label for="solver_result">Desired outcome:</label>
  <input type="text"
         required="required"
         pattern="^[\-+]?(?:\d+|\d+/[1-9]\d*|\d+\s+\d+/[1-9]\d*)$"
         id="solver_result"  list="solver_result-examples"
          data-error-message="enter one (fractional) number"
         value="24"/>
  <datalist id="solver_result-examples">
     <option value="24" />
     <option value="4 1/3" />
     <option value="41" />
     <option value="120" />
   </datalist>
   <br />
  <label for="solver_numbers">Input numbers:</label>
  <input type="text" id="solver_numbers"
         list="solver_numbers-examples"
         required="required"
         pattern="^[\-+]?(?:\d+|\d+/[1-9]\d*)(?:\s+(?:\d+|\d+/[1-9]\d*))*$"
          placeholder="Enter a few numbers (probably no more than 5)"
          data-error-message="enter one or more (fractional) numbers"
         />
   <datalist id="solver_numbers-examples">
     <option value="8 8 3 3" />
     <option value="4 7 7 7 5" />

   </datalist>
  <br />
  <output id="solver_output"  for="solver_result solver_numbers"> </output>
  <br />
  <button name="submit">go!</button>
</form>
++++

[%collapsible, title=java source code]
====
This is the source code for the above.
[source,java]
----
include::src/main/java/org/meeuw/math/test/Solver.java[indent=-]
----
====
[%collapsible, title=javascript]
====
This is the source code for the above.
[source,javascript]
----
include::resources/demo.js[indent=-,tag=solver]
----
====


== Dynamic date parsing

The `mihxil-time` module contain a 'dynamic date parser`

++++
<form id="dynamicdate" class="demo">
  <label for="dynamicdate_toparse">String to parse:</label> <input type="text" id="dynamicdate_toparse"  list="dynamicdate_toparse-examples" value="" />
   <datalist id="dynamicdate_toparse-examples">
   </datalist>
   <br />
  <output id="dynamicdate_output" for="dynamicdate_toparse"> </output>
  <br />
  <button name="submit">go!</button>
</form>
++++

[%collapsible, title=javascript]
====
This is the source code for the above.
[source,javascript]
----
include::resources/demo.js[indent=-,tag=dynamicdate]
----
====

