= math
:toc:
:toclevels: 4

image:https://travis-ci.org/mihxil/math.svg?[Build Status,link=https://travis-ci.org/mihxil/math]
image:https://github.com/mihxil/math/workflows/Maven%20Package/badge.svg[]
image:https://codecov.io/gh/mihxil/math/branch/master/graph/badge.svg[codecov,link=https://codecov.io/gh/mihxil/math]

Math and physics related classes. This is a hobby project which grew from the classes in 'mihxil-statistics' which are actually used.

== mihxil-math

The common dependency of the modules in the project. It provides the scaffolding for:

- abstract algebra's to ensure a common interface for basic operations.
- an 'uncertain number' interface, plus an implemention of a an algebraic field of uncertain number'
- a SPI for formatting the elements of abstract algebra's, and an implementation to format these uncertain number, using proper rounding and scientific notation.

=== Abstract Algebras

The idea is that every 'abstract algebra' consists of the implementation of two interfaces.

- One of the extensions of  link:mihxil-math/src/main/java/org/meeuw/math/abstractalgebra/AlgebraicElement.java[`org.meeuw.math.abstractalgebra.AlgebraicElement`] defines the properties of all elements of the algebra. It also should implement the actual operations like multiplication and addition.

- One of the corresponding extensions of link:mihxil-math/src/main/java/org/meeuw/math/abstractalgebra/AlgebraicStructure.java[`org.meeuw.math.abstractalgebra.AlgebraicStructure`], e.g.  link:mihxil-math/src/main/java/org/meeuw/math/abstractalgebra/AlgebraicStructure.java[`org.meeuw.math.abstractalgebra.Field`].

The terminology which is adopted is this:

|===
|Algebraic operation  | operator | operator name |

|addition | + | plus | link:mihxil-math/src/main/java/org/meeuw/math/abstractalgebra/AdditiveSemiGroupElement.java[`AdditiveSemiGroupElement`]
|subtraction | - | minus | link:mihxil-math/src/main/java/org/meeuw/math/abstractalgebra/AdditiveGroupElement.java[`AdditiveGroupElement`]
|multiplication |  ⋅  | times | link:mihxil-math/src/main/java/org/meeuw/math/abstractalgebra/MultiplicativeSemiGroupElement.java[`MultiplicativeSemiGroupElement`]
|division | / | dividedBy | link:mihxil-math/src/main/java/org/meeuw/math/abstractalgebra/MultiplicativeGroupElement.java[`MultiplicativeGroupElement`]

| negation |   | negation
| reciprocation | |  reciprocal

|===

It was chose that the method on the elements itself is the operator. So e.g.:

```java
  RationalNumber e1, e2, e3;
  ...
  e3 = e1.times(e2);

```

So, the 'operator names' are used as method names, and alway take the value of the element itself plus zero (for the unary operators) or one (for the binary operators) parameter, and create a new value from the same algebra.

Alternative terminology, like e.g. 'add' for addition would have been possible, but it was chosen to use those verbs when the operation is e.g. implemented staticly (`void add(e1, e2)`) or are modifying the element itself.

Most implementation are strictly read-only, but at least all algebraic operations themselves should be without side effects on the algebraic element itself.


==== Algebraic elements

For example it may be `org.meeuw.math.abstractalgebra.FieldElement` the have  addition, subtraction, multiplication, and division.

==== Algebraic structure

Every algebraic element object has a reference to (the same)  instance of this structure. The structure itself defines e.g. the 'cardinality'. If the cardinality is 'countable', the structure can also implement `org.meeuw.math.abstractalgebra.Streamable` to actually produce all possible elements.

The algebraic structure will also contain methods to obtain 'special elements' like the identity elements for multiplication and addition ('one' and 'zero')


== mihxil-statistics

Implementations of `UncertainDouble`, based on calculating standard deviations on sets of incoming data, and using that as the uncertainty value.

Also, it includes some classes to keep track of 'sliding window' values of averages.

== mihxil-physics

This module envolves mostly around `PhysicalNumber` and its derivitates. A `PhysicalNumber` is a `UncertainDouble` but the uncertainty is stated (it is  `Measurement`), and knows how to propagate those uncertainties when doing algebraic operations.

Also a `PhysicalNumber` can be assigned `Units`. This can be used for proper displaying the value, and for dimensional analysis.

== mihxil-algebra

This contains various implementations of the algebraic structure interfaces of `mihxil-math`. Like `RationalNumber` (modelling of rational numbers ℚ), and the rotation group SO(3).


.features
|===
| feature | element class | algebra class | description | features
| real numbers
|`org.meeuw.math.abstractalgebra.reals.RealNumber`
| `org.meeuw.math.abstractalgebra.reals.RealField`
| The field of real numbers, backed by the java primitive `double`
|

| arbitrary precision real numbers
| `org.meeuw.math.abstractalgebra.reals.BigDecimalElement`
| `org.meeuw.math.abstractalgebra.reals.BigDecimalField`
| The field of real numbers, backed by the java arbitrary precision 'BigDecimal'
|

| rational numbers
| `org.meeuw.math.abstractalgebra.rationalnumbers.RationalNumber`
| `org.meeuw.math.abstractalgebra.rationalnumbers.RationalNumbers`
| The field of rational numbers. Implemented using two arbitrary sized `BigIntegers`.
| Can be streamed (resulting an infinite stream of rational numbers)

| permutations
| `org.meeuw.math.abstractalgebra.permutations.Permutation`
| `org.meeuw.math.abstractalgebra.permutations.PermutationGroup`
| The permutation group. An example of a non-abelian finite group.
| Contains an implementation of 'all permutation'
a permuation is a function, and operators on any array of big enough size.
|===
