// Generated by 'make jars'. Do not edit.
// The cheerpj classpath, as present in resources/jars.
export const JARS = [
    "big-math-2.3.2.jar",
    "fastdoubleparser-2.0.1.jar",
    "mihxil-algebra-0.21-SNAPSHOT.jar",
    "mihxil-configuration-0.21-SNAPSHOT.jar",
    "mihxil-functional-1.21.jar",
    "mihxil-math-0.21-SNAPSHOT.jar",
    "mihxil-math-parser-0.21-SNAPSHOT.jar",
    "mihxil-physics-0.21-SNAPSHOT.jar",
    "mihxil-statistics-0.21-SNAPSHOT.jar",
    "mihxil-time-0.21-SNAPSHOT.jar",
    "original-mihxil-demo-0.21-SNAPSHOT.jar",
];
