= time
:toc:

image:https://img.shields.io/maven-central/v/org.meeuw/mihxil-time.svg[Maven Central,link=https://search.maven.org/artifact/org.meeuw/mihxil-time]
image:https://www.javadoc.io/badge/org.meeuw/mihxil-time.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw/mihxil-time]

This collects some utility related to time (actually to Durations and Instants). The main purpose is to provide a way to represent uncertain values of time, but it also provides some utilities for working with `Clock`, and a utility to parse 'relative' times.

== Uncertain `java.time` objects

This module provides things like `org.meeuw.time.UcertainInstant` and `org.meeuw.time.UncertainDuration', which are very similar to their `java.time` equivalents, but implement also `UncertainNumber`, so basically represents temporary objects _with an uncertaintiy_ in their value.

== Clocks

Because some uncertain values may be related to event rates, you may also need some things related to clocks. Especially, in test cases.

=== `TestClock`

A clock which must be manually 'ticked'. This  is mainly useful for testing purposes.

=== `UniqueClock`

A clock for which each call is guaranteed to result an Instant strictly after all previous calls. This can be used in tests, but also in production code, for example to ensure that events are always uniquely ordered.

== Dynamic date time parsing

Can be found in `DynamicDateTime`. E.g. parse things like 'tomorrow' to actual time instances. This is based on https://github.com/mmbase/mmbase/blob/MMBase-1_9/core/src/main/javacc/org/mmbase/util/dateparser/DateParser.jj[old MMBase code]. It is a https://javacc.org[javacc-grammar]. I modernized it to be fully based on `java.time` classes, and also incorporate the 'event searchers' I added to https://natty-parser.github.io[natty].

=== syntax

[NOTE]
====
This section is work in progress
====

The most basic idea is:
[source]
----
[<base time>] [modifications]*
----

==== base time
So, it starts with specifying some absolute time, which can be dynamic (refer to the current clock).

If no <base time> is specified, that implies 'now'.

Like so (where the current time is february 20, 2020)
|===
| Input | Output | remarks

| now  | 2020-02-20T20:20+01:00[Europe/Amsterdam] |
| | 2020-02-20T20:20+01:00[Europe/Amsterdam] | 'now' is the default, so the empty string is valid too.
| today | 2020-02-20T00:00+01:00[Europe/Amsterdam]  | start with some rounded value
| tohour | 2020-02-20T20:00+01:00[Europe/Amsterdam]  | other units than 'day' are possible too

| 1973-03-05T06:00 | 1973-03-05T06:00+01:00[Europe/Amsterdam] | just state it in ISO format
| 1973-03-05 | 1973-03-05T00:00+01:00[Europe/Amsterdam] | time is optional
|===

==== modifications

Then zero or more 'modifications' or 'offset' can be given. Most basically with + and -.

[options="header"]
|===
| Input | Output | remarks
| now + 5 minute | 2020-02-20T20:25+01:00[Europe/Amsterdam] |
| 2021-08-05T20:00 + 1 minute - 2 days | 2021-08-03T20:01+02:00[Europe/Amsterdam |
| next week | 2021-08-03T20:01+02:00[Europe/Amsterdam |
|===

There are also ways to set offsets which are not implicitly positive or negative. They just jump to some relevant time of some current period.

The offset can for example be something like 'this month', 'this day', or 'today', which basically arranges rounding

[options="header"]
|===
| Input | Output | remarks
| now this day | 2020-02-20T00:00+01:00[Europe/Amsterdam] |
| now tohour | 2020-02-20T20:00+01:00[Europe/Amsterdam] | 'to-' is an alias for that too.
| 2025-08-30 teatime | 2025-08-30T16:00+02:00[Europe/Amsterdam]
| some other our indication can be used too
|===

==== event searchers

Expression in quotes are 'event searchers'. They are basically a way to jump to occurrence of some registered event. For example, 'next "spring"' jumps to the next occurrence of the 'spring' equinox

`org.meeuw.time.eventsearchers.EventSearcher` is the Service loader interface that is used for that, and currently the following implementations are provided:

SeasonsEventSearcher:: Astronomical equinoxes and solstices 'spring', 'summer', 'fall' and 'winter'.
ChristianHolidaySearcher:: "Christmas Day", "Easter Sunday", "Easter Monday", "Ascension Day", "Pentecost Sunday" and "Pentecost Monday"
WellknownHolidaySearcher:: Well known (american) holidays like "New Year's Day", "Independence Day", "Labor Day", "Columbus Day", "Veterans Day" and "Thanksgiving".
WellknownIrregularHolidaySearcher:: Some (amarican) events that do not occur every year, like "Election day"

This is a bit US-centric because this was borrowed from natty, but it is possible to add your own event searchers by implementing the `EventSearcher` interface and registering it as a service provider.


==== Time zone

Finally, then entire thing can be postfixed and prefixed by an explicit timezone. The timezone defaults to `ZoneId#systemDefault`.

[options="header"]
|===
| Input | Output | remarks
| TZUTC today | 2025-11-23T00:00Z[UTC] |
|===



=== demo

ifdef::htmled[]
Here is a (working) demo for this.

include::../mihxil-demo/DEMO-datetime-source.adoc[leveloffset=2, tag=body]

It is a bit more elaborated link:https://mihxil.github.io/math/DEMO.html#demo_dynamicdate[here]

endif::[]
ifndef::htmled[]
Find link:https://mihxil.github.io/math/DEMO.html#demo_dynamicdate[a working demo] at github pages.
endif::[]

=== Comparison to MMBase

The parser in MMBase was actually implemented as an extension of `java.util.Date` itself (`org.mmbase.util.DynamicDate`), and was in that aspect simpler. But it was not a very good citizen because of that, because the actually value of the date could be 'dynamic', and sometimes that required some explicit conversion to a normal `java.util.Date` object. Turns out that date object can't be extended very well.

So, this idea was dropped. The parser was taken as is but, it was converted to parse to `java.time.ZonedDateTime` instead of `java.util.Date`, also a wrapper class was added `DynamicDateTime`, which can contain a bit of configuration for the parsing (like the `Clock` to use).

Also, inspired by natty, the 'event searchers' are added so the parser can also support holidays and other events like 'next spring'.



=== Comparison to natty

I always thought that for the use cases I saw natty was not a very good fit, and my own, old, mmbase utility was nicer.

- natty parses entire sentences, and tries to find all date-like strings in it, therefore, also it returns a complicated DateGroup object as a parse result
- DynamicDateTime always parses to one ZonedDateTime, or gives an exeption

The idea is that this can be used in configurations or requests that are dependent on the current time. E.g., 'give me all objects created between 2 weeks ago' and 'now'.  Using the parser, it can support this for you. It'll parse ISO dates, but also 'now' and similar things.


TODO: add more documentation
