= time

image:https://img.shields.io/maven-central/v/org.meeuw/mihxil-time.svg[Maven Central,link=https://search.maven.org/artifact/org.meeuw/mihxil-time]
image:https://www.javadoc.io/badge/org.meeuw/mihxil-time.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw/mihxil-time]

This collects some utility related to time (actually to Durations and Instants). The main purpose is to provide a way to represent uncertain values of time, but it also provides some utilities for working with `Clock`.

== Clocks

Because some uncertain values may be related to event rates, you may also need some things related to clocks. Especially, in test cases.

=== `TestClock`

A clock which must be manually 'ticked'. This  is mainly useful for testing purposes.

=== `UniqueClock`

A clock for which each call is guaranteed to result an Instant strictly after all previous calls. This can be used in tests, but also in production code, for example to ensure that events are always uniquely ordered.

== Dynamic date time parsing

Can be found in `DynamicDateTime`. E.g. parse things like 'tomorrow' to actual time instances. This is based on https://github.com/mmbase/mmbase/blob/MMBase-1_9/core/src/main/javacc/org/mmbase/util/dateparser/DateParser.jj[old mmbase code]. It is a https://javacc.org[javacc-grammar]. I modernized it to be fully based on `java.time` classes, and also incorporate the 'event searchers' I added to https://natty-parser.github.io[natty].

=== Comparison to natty

I always thought that for the use cases I saw natty is not a very good fit, and my own, old, mmbase utility was much nicer.

- natty parses entire sentences, and tries to find all date like string in it, therefore also it returns a complicated DateGroup object as a parse result
- DynamicDateTime always parses to one ZonedDateTime, or gives an exeption

The idea is that this can be used in configurations or requests that are dependent on the current time. E.g. 'give me all object created between 2 weeks ago' and 'now'.  Using the parser it can support this for you. It'll parse ISO dates, but also 'now' and similar things.


TODO: add more documentation
