= Shapes [[shapes]]
:gh: https://github.com/mihxil/math/
:ghblob: {gh}blob/main/
:ght: {ghblob}mihxil-shapes/src/main/java/
:ghraw: https://raw.githubusercontent.com/mihxil/math/main/
:docs: {ghraw}docs
:iwidth: 200





image:https://img.shields.io/maven-central/v/org.meeuw.math/mihxil-shapes.svg[Maven Central,link=https://search.maven.org/search?q=g:%22org.meeuw.math%22]
image:https://www.javadoc.io/badge/org.meeuw.math/mihxil-shapes.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw.math/mihxil-shapes]

The `shapes` modules contains implementations for several 2 and 3-dimensional shapes, like circles, spheres, and polygons.

[source,java]
----
include::src/test/java/org/meeuw/test/math/svg/SVGTest.java[tags=imports,indent=0]

....


include::src/test/java/org/meeuw/test/math/svg/SVGTest.java[tags=regularPolygons,indent=0]
----
image:{docs}/shapes/3-gon.svg[width={iwidth},titlle="triangle", link="{docs}/shapes/3-gon.svg"]
image:{docs}/shapes/4-gon.svg[width={iwidth},title="square"]
image:{docs}/shapes/5-gon.svg[width={iwidth},title="pentagon"]
image:{docs}/shapes/6-gon.svg[width={iwidth},title="hexagon"]
image:{docs}/shapes/7-gon.svg[width={iwidth},title="heptagon"]
image:{docs}/shapes/8-gon.svg[width={iwidth},title="octagon"]
image:{docs}/shapes/9-gon.svg[width={iwidth},title="nonagon"]
image:{docs}/shapes/10-gon.svg[width={iwidth},title="decagon"]

[source,java]
----
include::src/test/java/org/meeuw/test/math/svg/SVGTest.java[tags=otherShapes,indent=0]
----

image:{docs}/shapes/rectangle.svg[width={iwidth},title="rectangle"]
image:{docs}/shapes/circle.svg[width={iwidth},title="circle"]
image:{docs}/shapes/ellipse.svg[width={iwidth},title="ellipse"]
