= Shapes [[shapes]]
:gh: https://github.com/mihxil/math/
:ghblob: {gh}blob/main/
:ght: {ghblob}mihxil-shapes/src/main/java/
:ghraw: https://raw.githubusercontent.com/mihxil/math/main/
:docs: {ghraw}docs
:iwidth: 200





image:https://img.shields.io/maven-central/v/org.meeuw.math/mihxil-shapes.svg[Maven Central,link=https://search.maven.org/search?q=g:%22org.meeuw.math%22]
image:https://www.javadoc.io/badge/org.meeuw.math/mihxil-shapes.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw.math/mihxil-shapes]

The `shapes` modules contains implementations for several 2 and 3-dimensional shapes, like circles, spheres, and polygons.

[source,java]
----

import org.meeuw.math.shapes.dim2.*;
import org.meeuw.math.svg.SVG;
import org.w3c.dom.Document;

import static org.meeuw.math.uncertainnumbers.field.UncertainRealField.element;


....


@ParameterizedTest
@ValueSource(ints = {3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19})
public void regularPolygons(int n ) throws Exception {

    Document document = SVG.svg();
    SVG.svg(document,
        RegularPolygon.withCircumScribedRadius(n, element(100.0))
    );
    try (FileOutputStream fos = new FileOutputStream(new File(dest,  n +"-gon.svg"))) {
        SVG.marshal(document, new StreamResult(fos));
    }
}
----
image:{docs}/shapes/3-gon.svg[width={iwidth},titlle="triangle", link="{docs}/shapes/3-gon.svg"]
image:{docs}/shapes/4-gon.svg[width={iwidth},title="square"]
image:{docs}/shapes/5-gon.svg[width={iwidth},title="pentagon"]
image:{docs}/shapes/6-gon.svg[width={iwidth},title="hexagon"]
image:{docs}/shapes/7-gon.svg[width={iwidth},title="heptagon"]
image:{docs}/shapes/8-gon.svg[width={iwidth},title="octagon"]
image:{docs}/shapes/9-gon.svg[width={iwidth},title="nonagon"]
image:{docs}/shapes/10-gon.svg[width={iwidth},title="decagon"]

[source,java]
----

@Test
public void rectangle() throws Exception {
    Rectangle<?> rectangle = new Rectangle<>(element(100.0), element(180.0));
    Document svg = SVG.svg();
    SVG.svg(svg, rectangle);
    try (FileOutputStream fos = new FileOutputStream(new File(dest,  "rectangle.svg"))) {
        SVG.marshal(svg, new StreamResult(fos));
    }
}

@Test
public void circle() throws Exception {
    Circle<?> circle = new Circle<>(element(100.0));
    Document svg = SVG.svg();
    SVG.svg(svg, circle);
    try (FileOutputStream fos = new FileOutputStream(new File(dest,  "circle.svg"))) {
        SVG.marshal(svg, new StreamResult(fos));
    }
}

@Test
public void ellipse() throws Exception {
    Ellipse<?> ellipse = new Ellipse<>(element(100.0), element(80.0));
    Document svg = SVG.svg();
    SVG.svg(svg, ellipse);
    try (FileOutputStream fos = new FileOutputStream(new File(dest,  "ellipse.svg"))) {
        SVG.marshal(svg, new StreamResult(fos));
    }
}
----

image:{docs}/shapes/rectangle.svg[width={iwidth},title="rectangle"]
image:{docs}/shapes/circle.svg[width={iwidth},title="circle"]
image:{docs}/shapes/ellipse.svg[width={iwidth},title="ellipse"]
