= Shapes [[shapes]]
:gh: https://github.com/mihxil/math/
:ghblob: {gh}blob/main/
:ght: {ghblob}mihxil-shapes/src/main/java/
:ghraw: https://raw.githubusercontent.com/mihxil/math/main/
:docs: {ghraw}docs
:iwidth: 200





image:https://img.shields.io/maven-central/v/org.meeuw.math/mihxil-shapes.svg[Maven Central,link=https://search.maven.org/search?q=g:%22org.meeuw.math%22]
image:https://www.javadoc.io/badge/org.meeuw.math/mihxil-shapes.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw.math/mihxil-shapes]

The `shapes` modules contains implementations for several 2 and 3-dimensional shapes, like circles, spheres, and polygons.

[source,java]
----

import org.meeuw.math.abstractalgebra.integers.ModuloFieldElement;
import org.meeuw.math.shapes.dim2.*;
import org.meeuw.math.svg.SVG;
import org.meeuw.math.svg.SVGDocument;
import org.meeuw.math.uncertainnumbers.field.UncertainReal;

import static org.meeuw.math.svg.SVGDocument.defaultSVG;
import static org.meeuw.math.uncertainnumbers.field.UncertainRealField.element;


....


@ParameterizedTest
@ValueSource(ints = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20})
public void regularPolygons(int n ) throws Exception {

    RegularPolygon<UncertainReal> polygon = RegularPolygon.withCircumScribedRadius(n, element(100.0));

    SVGDocument document = defaultSVG()
        .withSize(size)
        .addGrid(b -> b.spacing(spacing))
        .addInfo(polygon)
        .addRegularPolygon(polygon, s -> s
            .circumscribedCircle(true)
            .inscribedCircle(true)
        )
        ;

    try (FileOutputStream fos = new FileOutputStream(new File(dest,  n +"-gon.svg"))) {
        SVG.marshal(document.buildDocument(), new StreamResult(fos));
    }
}
----
image:{docs}/shapes/3-gon.svg[width={iwidth},title="triangle", link="{docs}/shapes/3-gon.svg"]
image:{docs}/shapes/4-gon.svg[width={iwidth},title="square", link="{docs}/shapes/4-gon.svg"]
image:{docs}/shapes/5-gon.svg[width={iwidth},title="pentagon", link="{docs}/shapes/5-gon.svg"]
image:{docs}/shapes/6-gon.svg[width={iwidth},title="hexagon", link="{docs}/shapes/6-gon.svg"]
image:{docs}/shapes/7-gon.svg[width={iwidth},title="heptagon", link="{docs}/shapes/7-gon.svg"]
image:{docs}/shapes/8-gon.svg[width={iwidth},title="octagon", link="{docs}/shapes/8-gon.svg"]
image:{docs}/shapes/9-gon.svg[width={iwidth},title="nonagon", link="{docs}/shapes/9-gon.svg"]
image:{docs}/shapes/10-gon.svg[width={iwidth},title="decagon", link="{docs}/shapes/10-gon.svg"]

[source,java]
----
@Test
public void rectangle() throws Exception {
    Rectangle<UncertainReal> rectangle = new Rectangle<>(element(100.0), element(170.0));

    SVGDocument svg = defaultSVG()
        .withSize(size)
        .addGrid(b -> b.spacing( spacing))
        .addInfo(rectangle)
        .addPolygon(rectangle, s -> {
            s.circumscribedCircle(true);

        });
    //Document svg = SVG.svg();
    //SVG.svg(svg, rectangle);
    try (FileOutputStream fos = new FileOutputStream(new File(dest,  "rectangle.svg"))) {
        SVG.marshal(svg.buildDocument(), new StreamResult(fos));
    }
}

@Test
public void circle() throws Exception {
    Circle<UncertainReal> circle = new Circle<>(element(100.0));

    SVGDocument document = defaultSVG()
        .withSize(size)
        .addGrid(b -> b.spacing(spacing))
        .addInfo(circle)
        .addCircle(circle, s -> {})
        ;

    try (FileOutputStream fos = new FileOutputStream(new File(dest,  "circle.svg"))) {
        SVG.marshal(document.buildDocument(), new StreamResult(fos));
    }
}

@Test
public void ellipse() throws Exception {
    Ellipse<UncertainReal> ellipse = new Ellipse<>(element(100.0), element(80.0));

    SVGDocument document = defaultSVG()
        .withSize(size)
        .addGrid(b -> b.spacing(spacing))
        .addInfo(ellipse)
        .addEllipse(ellipse, s -> {s.circumscribedCircle(true);});

    try (FileOutputStream fos = new FileOutputStream(new File(dest,  "ellipse.svg"))) {
      SVG.marshal(document.buildDocument(), new StreamResult(fos));
    }
}
----

image:{docs}/shapes/rectangle.svg[width={iwidth},title="rectangle", link="{docs}/shapes/rectangle.svg"]
image:{docs}/shapes/circle.svg[width={iwidth},title="circle", link="{docs}/shapes/circle.svg"]
image:{docs}/shapes/ellipse.svg[width={iwidth},title="ellipse", link="{docs}/shapes/ellipse.svg"]
