---
name: build
# description: Builds, tests and publishes artifacts to sonatype snapshots
on:
  push:
    branches:
      - 'main'
      - '**-SNAPSHOT'
    paths-ignore:
      - 'README.adoc'
      - 'docs/**'
      - '.github/workflows/publish-documentation.yml'
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]
        java: [ 17 ]
        # also check (once) on latest
        include:
          - os: ubuntu-latest
            java: 25-ea
          - os: ubuntu-latest
            java: 21
          - os: ubuntu-latest
            java: 17
            rank: main
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:

      - uses: actions/checkout@v5
        with:
          # Use personal token for the commit at the end. otherwise publish-documentation action is not triggered
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      - name: Build with maven
        shell: bash
        run: |
          mvn -B -D"maven.test.failure.ignore=true" test
      - uses: codecov/codecov-action@v5
        if: ${{ matrix.rank == 'main' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
      - uses: MMProgrami/after-maven-action@main
        id: after_maven
        with:
          coverage: true
          determine_version: false
      - name: Use variable
        run: |
           echo "The value is ${{ steps.after_maven.outputs.MAVEN_TESTS_FAILED}}"
           echo "The values are ${{ steps.after_maven.outputs}}"
        if: always()
      - name: Deploy to central
        # We deploy with the -D setting. This way the 'no-deploy' profile is deactivated, arranging that the modules in that are not deployed
        # It also sets the default target to deploy
        timeout-minutes: 10
        run: mvn -B -DskipTests -Ddeploy deploy
        if: ${{ matrix.rank == 'main' }}
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - name: Commit generated graphviz file if it changed
        uses: EndBug/add-and-commit@v9
        if: ${{  matrix.rank  == 'main' }}
        with:
          message: Automated update of dot.m4
          add: docs/algebras.dot.m4


