---
name: build
# description: Builds, tests and publishes artifacts to sonatype snapshots
on:
  push:
    branches:
      - 'main'
      - '**-SNAPSHOT'
    paths-ignore:
      - 'README.adoc'
      - 'docs/**'
      - '.github/workflows/publish-documentation.yml'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 17 ]
        # also check (once) on latest
        include:
          - os: ubuntu-latest
            java: 24
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:
      - name: Cancel previous Action
        uses: styfle/cancel-workflow-action@0.12.1
      - uses: actions/checkout@v4
        with:
          # Use personal token for the commit at the end. otherwise publish-documentation action is not triggered
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
      - name: Build with Maven
        run: mvn -B -fae
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.20.0
        if: always() &&  runner.os == 'Linux'
        with:
          files: "**/target/surefire-reports/*.xml"
          check_name: Tests results
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2.20.0
        if: always() &&  runner.os == 'Windows'
        with:
          files: "**/target/surefire-reports/*.xml"
          check_name: Tests results
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/macos@v2.20.0
        if: always() && runner.os == 'macOS'
        with:
          files: "**/target/surefire-reports/*.xml"
          check_name: Tests results
      - uses: codecov/codecov-action@v4
        if: ${{ github.event_name == 'push'  && ! cancelled() && runner.os == 'Linux' && matrix.java == '17'}}
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
      - name: Deploy with Maven
        run: mvn -B -Ddeploy  -DskipTests=true deploy
        if: ${{ github.event_name == 'push'  && ! cancelled() && runner.os == 'Linux' && matrix.java == '17'}}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - name: Commit generated dot file if it changed
        uses: EndBug/add-and-commit@v9
        if: ${{ runner.os == 'Linux' && matrix.java == '17'}}
        with:
          message: Automated update of dot.m4
          add: docs/algebras.dot.m4
