---
name: build
# description: Builds, tests and publishes artifacts to sonatype snapshots
on:
  push:
    branches:
      - 'main'
      - '**-SNAPSHOT'
    paths-ignore:
      - 'README.adoc'
      - 'docs/**'
      - '.github/workflows/publish-documentation.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - name: Cancel previous Action
        uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v3
        with:
          # Use personal token for the commit at the end. otherwise publish-documentation action is not triggered
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          set
          mvn -B -fae
      - uses: codecov/codecov-action@v2
        if: always()
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.32
        if: always()
        with:
          files: "**/target/surefire-reports/*.xml"
      - uses: crazy-max/ghaction-import-gpg@v4.3.0
        with:
           gpg_private_key: ${{ secrets.GPG_SECRET_KEY }}
           passphrase: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - name: Create settings.xml
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: '[{"id": "ossrh", "username": "mihxil", "password": "${{secrets.OSSRH_PASSWORD}}"}]'
      - name: Deploy with Maven
        run: mvn -B -Ddeploy  -DskipTests=true
        if: ${{ github.event_name == 'push' }}
      - name: Commit generated dot file if it changed
        uses: EndBug/add-and-commit@v9
        with:
          message: Automated update of dot.m4
          add: docs/algebras.dot.m4
