---
name: build
# description: Builds, tests and publishes artifacts to sonatype snapshots
on:
  push:
    branches:
      - 'main'
      - '**-SNAPSHOT'
    paths-ignore:
      - 'README.adoc'
      - 'docs/**'
      - '.github/workflows/publish-documentation.yml'
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]
        java: [ 17 ]
        target: [ test  ]
        # also check (once) on latest
        include:
          - os: ubuntu-latest
            java: 24
            target: test
            mainbuild: true
          - os: ubuntu-latest
            java: 17
            target: deploy
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:

      - uses: actions/checkout@v5
        with:
          # Use personal token for the commit at the end. otherwise publish-documentation action is not triggered
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      - name: Build with Maven ${{ matrix.deploy }}
        run: mvn -B -D"maven.test.failure.ignore=true" -D${{ matrix.target }}
        timeout-minutes: 10
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - uses: codecov/codecov-action@v5
        if:  ${{ matrix.mainbuild == 'true' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
      - uses: MMProgrami/after-maven-action@main
      - name: Commit generated graphviz file if it changed
        uses: EndBug/add-and-commit@v9
        if: ${{  matrix.mainbuild  == 'true' }}
        with:
          message: Automated update of dot.m4
          add: docs/algebras.dot.m4
