---
name: build
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.adoc'
      - '.github/workflows/publish-documentation.yml'


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B -fae
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "**/target/surefire-reports/*.xml"
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy with Maven
        run: OSSRH_PASSWORD=${{ secrets.OSSRH_PASSWORD }} mvn -B -Ddeploy  -DskipTests=true -s $GITHUB_WORKSPACE/.github/settings.xml -Dgpg.skip=true
        if: ${{ github.event_name == 'push' }}
      - name: push changes
        # after
        run: |
          git config --global user.name 'github actions'
          git config --global user.email 'github@meeuw.org'
          git checkout main
          git diff-index --quiet HEAD || git commit -m "Automated update of dot.m4" docs/algebras.dot.m4
          echo pushing
          git push
        if: ${{ github.event_name == 'push' }}

