---
name: build
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.adoc'
      - 'docs/**'
      - '.github/workflows/publish-documentation.yml'


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - name: Cancel previous Action
        uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2
        with:
          # Use personal token for the commit at the end. otherwise publish-documentation action is not triggered
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          set
          mvn -B -fae
      - uses: codecov/codecov-action@v2
        if: always()
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.31
        if: always()
        with:
          files: "**/target/surefire-reports/*.xml"
      - uses: crazy-max/ghaction-import-gpg@v3
        with:
           gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
           passphrase: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - name: Deploy with Maven
        run: OSSRH_PASSWORD=${{ secrets.OSSRH_PASSWORD }} mvn -B -Ddeploy  -DskipTests=true -s $GITHUB_WORKSPACE/.github/settings.xml -Dgpg.skip=false
        if: ${{ github.event_name == 'push' }}
      - name: Commit generated dot file if it changed
        uses: EndBug/add-and-commit@v7
        with:
          message: Automated update of dot.m4
          add: docs/algebras.dot.m4
