---
name: build
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.adoc'
      - '.github/workflows/publish-documentation.yml'


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B -fae
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.25
        if: always()
        with:
          files: "**/target/surefire-reports/*.xml"
          log_level: DEBUG
          root_log_level: DEBUG
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy with Maven
        run: OSSRH_PASSWORD=${{ secrets.OSSRH_PASSWORD }} mvn -B -Ddeploy  -DskipTests=true -s $GITHUB_WORKSPACE/.github/settings.xml -Dgpg.skip=true
        if: ${{ github.event_name == 'push' }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated update of dot.m4
          file_pattern: docs/algebras.dot.m4
        if: ${{ github.event_name == 'push' }}

