name: Reduce README
on:
  push:
    paths:
    - README-source.adoc
    - '*/README-source.adoc'
    - '.github/workflows/reduce-readme.yml'
    - '**/examples/**'
    branches: ['**']
jobs:
  asciidoctor:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Install Asciidoctor Reducer
      run: sudo gem install asciidoctor-reducer
    - name: Reduce README
      run: |
        asciidoctor-reducer -o README.adoc README-source.adoc
        asciidoctor-reducer -o mihxil-configuration/README.adoc mihxil-configuration/README-source.adoc
        asciidoctor-reducer -o mihxil-theories/README.adoc mihxil-theories/README-source.adoc
    - name: Commit and Push README
      uses: EndBug/add-and-commit@v9
      with:
        add: '["README.adoc", "mihxil-configuration/README.adoc", "mihxil-theories/README.adoc"]'
