---
name: release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    if: startsWith(github.ref, 'refs/heads/REL-')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Create settings.xml
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "ossrh", "username": "mihxil", "password": "${{secrets.OSSRH_PASSWORD}}"}]'
      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          passphrase: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - name: Release
        run: |
          git config --global user.name 'github actions'
          git config --global user.email 'github@meeuw.org
          mvn --batch-mode  -Darguments=-DskipTests  -DpushChanges=false release:prepare
          git push --atomic -v --follow-tags
          mvn -Pdeploy,ossrh --batch-mode -Darguments=-DskipTests release:perform
